### ISSUE TITLE
Typing text not coming up + other stuff

### ISSUE THREAD

**Issue by codingMASTER398** [respecting/kahoot-bot#1]
Hey respecting!

I have modded this project and put it on my youtube channel, (great job by the way!)
https://www.youtube.com/channel/UCihOD-Ot4Im5RLKyZrvALYg

But i have noticed something, when i do a bot and control it and/or do 2 step,
the text i type in does not show at all.
Could you somehow fix this or is this... not fixable?

One other thing, this is really good, and as i said, i modded it and uploaded it.
I think, though, this should have its own website for the .exe download

I am asking for permission to make a weebly website (that does put you in there) for the download, some demos and FAQ.
I think this is a quite good idea because, well, this is the best kahoot bot i have ever seen!

-codingMASTER398

**Comment by respecting** [comment]
Yeah, you can make a weebly site. I actually poorly made 2step and bot control because my brain was hurting. I'll get on to it when I have free time.

**Comment by codingMASTER398** [comment]
Hey again!

I do not how to make a web version of the bot, as i do not know how to put the node modules into a HTML 5 document.
The website will have a download to a .exe file packaged with pkg.

Also, i will properly credit the github and not put any caps on.

oh lord 5000 bots
![image](https://user-images.githubusercontent.com/55938439/93273087-56e5b200-f7fa-11ea-90db-39adaca52c3f.png)
time to get a coffee

**Comment by respecting** [comment]
I've already made a [web](https://github.com/respecting/kahoot-bot/tree/web) version, pkg already includes the html file I made. Thanks for understanding!

**Comment by codingMASTER398** [comment]
Oooh

Do you mind if i make it a bit more appealing to people who click on it and host it?

I will add a few more options and put the github in, by the way.

**Comment by respecting** [comment]
Sure, maybe add me on my discord and we can talk. whenlifegivesyoulemons#5578

**Comment by codingMASTER398** [comment]
It says this:
![image](https://user-images.githubusercontent.com/55938439/93278384-d6c64900-f807-11ea-9ccd-62d93fcf33ac.png)

Add me instead, codingMASTER398#2718
