### ISSUE TITLE
):

### ISSUE THREAD

**Issue by codingMASTER398** [respecting/kahoot-bot#2]
):

**Comment by codingMASTER398** [comment]
i thought we could make a website for the kahoot bot...
😢
![image](https://user-images.githubusercontent.com/55938439/93406446-055d2600-f8d3-11ea-9a04-1de1e6be4ec4.png)

**Comment by codingMASTER398** [comment]
i can see you cannot respect others, im going to make the website as good as possible and host it myself.

**Comment by respecting** [comment]
oh boy you better fucking add my license or i'll dmca your shit down

**Comment by codingMASTER398** [comment]
i did

**Comment by respecting** [comment]
https://www.youtube.com/watch?v=_NesrSza_G8 in here you didnt 👎

**Comment by codingMASTER398** [comment]
https://youtu.be/_NesrSza_G8?t=98
i did

**Comment by respecting** [comment]
thats not a fucking license it is credit
MIT License states:
`The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.`

**Comment by codingMASTER398** [comment]
is it not in there? i can update it and put the licence in the files
