### ISSUE TITLE
last statement: taking down video

### ISSUE THREAD

**Issue by codingMASTER398** [respecting/kahoot-bot#6]
hi there, because the .exe shown in the video did not contain a licence, i will be taking down the video around 5PM tomorrow AEST.

an updated version will then be uploaded that does contain a licence.

Please dont DMCA me, im just a kid

**Comment by respecting** [comment]
yo holy shit just comment onto the #2 one stop making all of these issues

**Comment by codingMASTER398** [comment]
sorry 😢

**Comment by codingMASTER398** [comment]
https://kahootflood.weebly.com/
