### ISSUE TITLE
# node flood.js No, I don't think I will error

### ISSUE THREAD

**Issue by TheRealPankea** [respecting/kahoot-bot#8]
Hi I installed everything but it give me : 
![Screenshot_20201007-095228_Termux](https://user-images.githubusercontent.com/71831167/95302898-d3603380-0882-11eb-90d9-32d98afa6324.png)

No, I don't think I will

**Comment by respecting** [comment]
download from [here](https://github.com/respecting/kahoot-bot/tree/c0230f56c3ef85fdcb543d6f44ffda3b4a842dde)
master branch is in the works
